flags: {}
packages:
- '.'
allow-newer: true
extra-deps:
- haskoin-core-0.4.0
- aeson-0.8.1.1
- base-orphans-0.5.3
- murmur3-1.0.1
- pbkdf-1.1.1.1
- secp256k1-0.4.5
- text-1.2.2.0
- vector-0.10.12.3
resolver: lts-5.3
